#docker run -d --rm -w /opt -v $(pwd):/opt -p 3000:3000 --name angulartut node:alpine npm start
angular:
  image: node:alpine
  ports:
    - "3000:3000"
  volumes:
    - "$PWD":/opt
  entrypoint:
    - /opt/entrypoint.sh
